# brew tap homebrew/boneyard
# brew bundle in directory with Brewfile

# update and upgrade
update --rebase
upgrade

# good taps
# tap homebrew/versions
tap homebrew/dupes

install tig
install reattach-to-user-namespace
install fish
install terminal-notifier
install emacs --cocoa

# from dupes
install whois

# link apps
linkapps --local

# cleanup
cleanup

# Cask all the things

tap caskroom/cask
install brew-cask

cask install airfoil
cask install totalspaces
cask install caffeine
cask install kensington-trackball-works
cask install iterm2
cask install clipmenu
cask install plex-home-theater
cask install synology-cloud-station
cask install startninja
cask install viber
cask install vlc
cask install karabiner
cask install seil
cask install flash-player
cask install amethyst
cask install opera
cask install vox
cask install mactracker

cask install betterzipql
cask install qlcolorcode
cask install qlmarkdown
cask install qlprettypatch
cask install qlstephen
cask install quicklook-csv
cask install quicklook-json
cask install suspicious-package
cask install webpquicklook

# cask cleanup
cask cleanup
