---
keys:
  - &pgp_suvash D9202921A7F1C7E826065EB0B990712C8FBFC4CC!
  - &age_lle age14t3gdtpq0ar9kzznlqyjuvqs4cfw2yleqm2hz28mqws89p75e39sm484tt
  - &age_paathshala age18x5naguqtajnml26hjdltuesg30dpse2ejzper6zpdquvklq6f0qy59yss
creation_rules:
  - path_regex: hosts/lle/sops/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *pgp_suvash
        age:
          - *age_lle
  - path_regex: hosts/paathshala/sops/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *pgp_suvash
        age:
          - *age_paathshala

