---
keys:
  - &pgp_suvash D9202921A7F1C7E826065EB0B990712C8FBFC4CC!
  - &age_lle age1xsgfyz7j5mrnn4stacptjrxm0d4kuzqwzljfz04mds330nt8tp8qkzkdj2
creation_rules:
  - path_regex: hosts/lle/sops/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *pgp_suvash
        age:
          - *age_lle

