tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"

tap "brewsci/bio"
tap "brewsci/science"

cask_args appdir: "/Applications"

brew "awscli"
brew "bat"
brew "binutils"
brew "coreutils"
brew "curl"
brew "cloc"
brew "cmatrix"
brew "dfc"
brew "diffutils"
brew "diff-so-fancy"
brew "exa"
brew "fd"
brew "findutils", args: ["with-default-names"]
brew "fish"
brew "fzf"
brew "gawk"
brew "gcal"
brew "git"
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar", args: ["with-default-names"]
brew "gnu-which", args: ["with-default-names"]
brew "gnutls"
brew "gnupg"
brew "grep", args: ["with-default-names"]
brew "gzip"
brew "htop"
brew "less"
brew "lsof"
brew "make"
brew "mas"
brew "neovim"
brew "ngrep"
brew "packer"
brew "pinentry-mac"
brew "reattach-to-user-namespace"
brew "rg"
brew "rlwrap"
brew "rustup-init"
brew "shellcheck"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "unrar"
brew "unzip"
brew "vim"
brew "watch"
brew "wget"
brew "whois"
brew "xsv"

cask "alfred"
cask "appcleaner"
cask "caffeine"
cask "docker"
cask "emacs"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "java8"
cask "karabiner-elements"
cask "kensington-trackball-works"
cask "keybase"
cask "mendeley"
cask "nordvpn"
cask "notion"
cask "opera"
cask "qlmarkdown"
cask "qlprettypatch"
cask "quicklook-csv"
cask "quicklook-json"
cask "spectacle"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
cask "vuescan"
cask "wacom-tablet"
cask "webpquicklook"

mas "Flycut", id: 442160987
mas "HardwareGrowler", id: 475260933
mas "LastPass", id: 926036361
mas "The Unarchiver", id: 425424353
mas "Slack", id: 803453959

# Manual install
# Fuji Raw Studio
# Adobe + Nik
# EIZO ColorNavigator
# Ableton Live Suite
# Melodics
