tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

tap "brewsci/bio"
tap "brewsci/science"

cask_args appdir: "/Applications"

brew "awscli"
brew "bat"
brew "bash"
brew "binutils"
brew "coreutils"
brew "curl"
brew "cmatrix"
brew "dfc"
brew "diffutils"
brew "diff-so-fancy"
brew "exa"
brew "fd"
brew "findutils"
brew "fish"
brew "fzf"
brew "gawk"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gnutls"
brew "gnupg"
brew "grep"
brew "gzip"
brew "htop"
brew "iamy"
brew "jq"
brew "kubectx"
brew "less"
brew "lsof"
brew "make"
brew "mas"
brew "mosh"
brew "ngrep"
brew "pgcli"
brew "pinentry-mac"
# brew "reattach-to-user-namespace"
brew "rg"
brew "rlwrap"
brew "shellcheck"
brew "speedtest-cli"
brew "sops"
brew "terraform"
# brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tree"
brew "unrar"
brew "unzip"
brew "vim"
brew "watch"
brew "wget"
brew "whois"
brew "xsv"

cask "alfred"
cask "amethyst"
cask "anki"
cask "bitwarden"
cask "brave-browser"
cask "caffeine"
cask "dictionaries"
cask "disk-inventory-x"
cask "docker"
cask "emacs"
cask "firefox"
cask "font-fira-code"
cask "google-cloud-sdk"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
# cask "kensington-trackball-works"
cask "nordvpn"
cask "opera"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
# cask "wacom-tablet"

mas "Flycut", id: 442160987
mas "HardwareGrowler", id: 475260933
mas "The Unarchiver", id: 425424353
mas "Slack", id: 803453959
mas "Battery Health 2", id: 1120214373

# Manual install
# Nik Collection
# Skylum Luminar etc.
# Ableton Live
# Affinity Photo
# Capture One
# Fuji Raw Studio
# Benq Palette Master ELement
# Chrysalis
# Zoom
