# brew tap homebrew/boneyard
# brew bundle in directory with Brewfile

# update and upgrade
update --rebase
upgrade

# good taps
# tap homebrew/versions
tap homebrew/dupes

install ag
install ncdu
install dfc
install wget
install htop
install lsof
install tree
install make
install watch
install unzip
install less
install tig
install fish
install vim
install emacs --with-cocoa
install tmux
install reattach-to-user-namespace

# from dupes
install whois

# link apps
linkapps --local

# cleanup
cleanup

# Cask all the things

tap caskroom/cask
install brew-cask

cask install airfoil
cask install alfred
cask install caffeine
cask install kensington-trackball-works
cask install iterm2
cask install clipmenu
cask install plex-home-theater
cask install synology-cloud-station
cask install viber
cask install vlc
cask install karabiner
cask install seil
cask install spectacle
cask install flash-player
cask install vox
cask install mactracker
cask install virtualbox

cask install betterzipql
cask install qlcolorcode
cask install qlmarkdown
cask install qlprettypatch
cask install qlstephen
cask install quicklook-csv
cask install quicklook-json
cask install suspicious-package
cask install webpquicklook

# cask cleanup
cask cleanup
