#!/usr/bin/env bash

# Kill ssh-agent
killall ssh-agent

# Gnome Keyring for all things
eval $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# Export environment variables if present
if [ -f $HOME/.env ] ; then
    export $("$HOME/.env")
fi

exec xmonad-session
