#!/usr/bin/env bash

# Kill ssh-agent
killall ssh-agent

# Gnome Keyring for all things
eval $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# Export for Java/Xmonad workalong
export _JAVA_AWT_WM_NONREPARENTING=1

exec xmonad-session
