#!/usr/bin/env bash

# Kill ssh-agent
killall ssh-agent
#
# # Gnome Keyring for all things
# eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
# export SSH_AUTH_SOCK

# Gnome Keyring
eval $(gnome-keyring-daemon --start --components=pkcs11,secrets)

# GPG Agent with SSH
gpg-connect-agent /bye
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# Export environment variables if present
if [ -f $HOME/.env ] ; then
    export $("$HOME/.env")
fi

exec xmonad-session
